name: maven-git project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      # - name: Set JDK
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      - name: jdk version knowing
        run: java -version
      - name: Maven Version
        run: mvn -version
      - name: Validate
        run: mvn validate
      - name: Test
        run: mvn test
      - name: Package
        run: mvn package
        
