name: maven-git project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: jdk version knowing
        uses: java -version
      - name: maven version
        uses: mvn -version
        
